### PR TITLE
Add support for centos/rhel and bump to 1.5.0

### PR DESCRIPTION
**Pull request by mattsmitton**

### CODE REVIEW

**Comment by mattsmitton** [comment]
Tested on centos 6.6

**Comment by kimtore** [comment]
Hi @beeerd, thanks for the patch.

Your code does not converge in Test Kitchen on a Centos 6.6 box. Also, the documentation is not updated, neither is `metadata.rb` nor `.kitchen.yml`. Sorry, but I can't merge this in the current state. Please also do not update the version number when sending merge requests.

We'd love to merge CentOS support, so if you'll address these issues, and make sure the code passes `kitchen verify centos`, I'll take a look again!

Here's the error from Test Kitchen:

```
================================================================================
Error executing action `upgrade` on resource 'yum_package[php-pear-net-curl]'
================================================================================
Chef::Exceptions::Package
-------------------------
No candidate version available for php-pear-net-curl
```

**Comment by mattsmitton** [comment]
Drat! 

Thank you for your review and input, I suspect I need to add the epel repository cookbook as a dependency. I admit I did not do a full test from scratch on a vagrant vm, but I will be sure to do that before my next pull request.

Cheers

**Comment by kimtore** [comment]
Hi @beeerd,

Any progress on RHEL support, or should I close the pull request?

Regards

**Pull request closed without merging**
